// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UDMT.Domain.Context;

#nullable disable

namespace UDMT.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250325214900_SubclassService")]
    partial class SubclassService
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UDMT.Domain.Entity.CharClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasMagic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHomebrew")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProficencyBonus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CharClasses");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.CharClassSavingThrow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeType")
                        .HasColumnType("int");

                    b.Property<int>("CharClassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharClassId");

                    b.ToTable("CharClassSavingThrows");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.CharSubclass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharClassId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GrantsMagic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHomebrew")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharClassId");

                    b.ToTable("CharSubclasses");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharClassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int?>("SubclassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharClassId");

                    b.HasIndex("RaceId");

                    b.HasIndex("SubclassId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.CharacterAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeType")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterAttributes");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.CharacterSavingThrow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeType")
                        .HasColumnType("int");

                    b.Property<int>("BonusOverride")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsProficient")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterSavingThrows");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.CharacterSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BonusOverride")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsProficient")
                        .HasColumnType("bit");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SkillId");

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.ClassSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharClassId")
                        .HasColumnType("int");

                    b.Property<bool>("IsProficient")
                        .HasColumnType("bit");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("CharClassId", "SkillId")
                        .IsUnique();

                    b.ToTable("ClassSkills");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharClassId")
                        .HasColumnType("int");

                    b.Property<int?>("CharSubclassId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CharClassId");

                    b.HasIndex("CharSubclassId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHomebrew")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequireSubrace")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.RaceAttributeBonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeType")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceAttributeBonuses");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.RaceRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int?>("SubraceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubraceId");

                    b.HasIndex("RaceId", "SubraceId")
                        .IsUnique()
                        .HasFilter("[SubraceId] IS NOT NULL");

                    b.ToTable("RaceRelations", (string)null);
                });

            modelBuilder.Entity("UDMT.Domain.Entity.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.CharClassSavingThrow", b =>
                {
                    b.HasOne("UDMT.Domain.Entity.CharClass", "CharClass")
                        .WithMany("SavingThrowProficiencies")
                        .HasForeignKey("CharClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharClass");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.CharSubclass", b =>
                {
                    b.HasOne("UDMT.Domain.Entity.CharClass", "CharClass")
                        .WithMany("Subclasses")
                        .HasForeignKey("CharClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharClass");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.Character", b =>
                {
                    b.HasOne("UDMT.Domain.Entity.CharClass", "CharClass")
                        .WithMany()
                        .HasForeignKey("CharClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UDMT.Domain.Entity.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UDMT.Domain.Entity.CharSubclass", "Subclass")
                        .WithMany()
                        .HasForeignKey("SubclassId");

                    b.Navigation("CharClass");

                    b.Navigation("Race");

                    b.Navigation("Subclass");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.CharacterAttribute", b =>
                {
                    b.HasOne("UDMT.Domain.Entity.Character", "Character")
                        .WithMany("Attributes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.CharacterSavingThrow", b =>
                {
                    b.HasOne("UDMT.Domain.Entity.Character", "Character")
                        .WithMany("SavingThrows")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.CharacterSkill", b =>
                {
                    b.HasOne("UDMT.Domain.Entity.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UDMT.Domain.Entity.Skill", "Skill")
                        .WithMany("CharacterSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.ClassSkill", b =>
                {
                    b.HasOne("UDMT.Domain.Entity.CharClass", "CharClass")
                        .WithMany("ClassSkills")
                        .HasForeignKey("CharClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UDMT.Domain.Entity.Skill", "Skill")
                        .WithMany("ClassSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CharClass");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.Feature", b =>
                {
                    b.HasOne("UDMT.Domain.Entity.CharClass", null)
                        .WithMany("Features")
                        .HasForeignKey("CharClassId");

                    b.HasOne("UDMT.Domain.Entity.CharSubclass", null)
                        .WithMany("Features")
                        .HasForeignKey("CharSubclassId");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.RaceAttributeBonus", b =>
                {
                    b.HasOne("UDMT.Domain.Entity.Race", "Race")
                        .WithMany("AttributeBonuses")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.RaceRelation", b =>
                {
                    b.HasOne("UDMT.Domain.Entity.Race", "Race")
                        .WithMany("RaceRelations")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UDMT.Domain.Entity.Race", "Subrace")
                        .WithMany()
                        .HasForeignKey("SubraceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Race");

                    b.Navigation("Subrace");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.CharClass", b =>
                {
                    b.Navigation("ClassSkills");

                    b.Navigation("Features");

                    b.Navigation("SavingThrowProficiencies");

                    b.Navigation("Subclasses");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.CharSubclass", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.Character", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("SavingThrows");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.Race", b =>
                {
                    b.Navigation("AttributeBonuses");

                    b.Navigation("RaceRelations");
                });

            modelBuilder.Entity("UDMT.Domain.Entity.Skill", b =>
                {
                    b.Navigation("CharacterSkills");

                    b.Navigation("ClassSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
